layout: "main"
#logger: "console"
appname: "Saml2Test"

idp: "http://localhost:8880/metadata.xml"
issuer: "https://netsaml2-testapp.local"
url: "https://netsaml2-testapp.local"
cert: "sign-certonly.pem"
key: "sign-nopw-cert.pem"
cacert: "saml_cacert.pem"
slo_url_soap: "/slo-soap"
slo_url_redirect: "/sls-redirect-response"
slo_url_post: "/sls-post-response"
acs_url_post: "/consumer-post"
acs_url_artifact: "/consumer-artifact"
org_name: "Net::SAML2 Saml2Test"
org_display_name: "Saml2Test app for Net::SAML2"
org_contact: "saml2test@example.com"
error_url: "/error"
