name: linux

on:
  - push

jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.12'
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Install Crypt::OpenSSL::VerifyX509
        run: |
          curl -sL https://cpanmin.us/ | perl - -nq inc::Module::Install \
          Module::Install::AuthorRequires Module::Install::AuthorTests \
          Test::NoTabs Test::Pod Test::Pod::Coverage Test::More Crypt::OpenSSL::X509;
          git clone https://github.com/timlegge/perl-Crypt-OpenSSL-VerifyX509.git;
          cd perl-Crypt-OpenSSL-VerifyX509;
          perl Makefile.PL;
          make install;
          cd ..;
      - name: Install Net::SAML2 Depends
        run: |
          apt-get install libxml2-dev make gcc;
          curl -sL https://cpanmin.us/ | perl - -nq --installdeps . ;
      - name: Build Module
        run: |
          perl Makefile.PL;
          make
      - name: Run Tests
        run: |
          prove -lr -l -b -I inc t
